notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required

language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
env:
    REOP="fcweb"
    VERSION="1.0.0"
    BUILDER_PACKAGE="$REOP-$VERSION-$TRAVIS_COMMIT.tar.gz"

# cache components
before_install:
    - env
    - npm install
install:
    - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
    - curl airdb.com/install
    - ls -l
    - sudo pip install s3cmd
    - sudo pip install aws
before_script:
    - curl airdb.com/before_script
script:
    - npm run build
    # - tree
    - ls -l
    - tar -zvcf ${BUILDER_PACKAGE}.tar.gz dist
    - ls -l
    - pwd
after_success:
    - s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY ls -r s3://airdb.me/${REPO}/
    - s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY put ${BUILDER_PACKAGE}.tar.gz s3://airdb.me/${REPO}/
    - s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY put --acl-public dist/* -r s3://airdb.me/
    - s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY ls -r s3://airdb.me/
    #    - curl  "https://awsapi.airdb.vip/travis-ci?status=success&info=https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
    #after_failure:
    #    - curl  "https://awsapi.airdb.vip/travis-ci?status=failure&info=https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
before_deploy:
    - curl airdb.com/before_deploy
#deploy:
    #- provider: releases
    #  user: $GITHUB_USERNAME
    #  password: $GITHUB_PASSWORD
    #  file: fcweb.tar.gz
    #  skip_cleanup: true
    #  on: 
    #    branch: master
    #  #tags: true
    #    provider: s3
    #    access_key_id: $AWS_ACCESS_KEY_ID
    #    secret_access_key: $AWS_SECRET_KEY
    #    bucket: $BUCKET
    #    #local_dir: "./releases"
    #    key: "fcweb.tar.gz"
    #    upload-dir: "fcweb"
    #    #skip_cleanup: false
    #    #default_text_charset: 'utf-8'
#    on:
#        branch: master
after_deploy:
    - curl airdb.com/after_deploy
after_script:
    - curl airdb.com/after_scritp
