notifications:
  email:
    - dean@airdb.com
dist: trusty
sudo: required

language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
env:
  REPO="fcweb"
  VERSION="1.0.0"
  BUILDER_PACKAGE="$REPO-$VERSION-$TRAVIS_COMMIT.tar.gz"
  WechatMSG="https://aws.airdb.io/wechat/sendmsg"

# cache components
before_install:
    - env
    - npm install
install:
    - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
    - curl airdb.com/install
    - ls -l
    - sudo pip install awscli
before_script:
    - curl airdb.com/before_script
script:
    - npm run build
    # - tree
    - ls -l
    - cp -f robots.txt favicon.ico dist/
    - tar -zvcf ${BUILDER_PACKAGE} dist
    - ls -l
    - pwd
    - aws --version
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key  ${AWS_SECRET_ACCESS_KEY}
    - aws configure get aws_secret_access_key
    - echo ${AWS_SECRET_ACCESS_KEY}
after_success:
    - cat ~/.aws/credentials | tail -n1
    - aws s3 ls airdb.io
    - aws s3 cp ${BUILDER_PACKAGE} airdb.io
    - aws s3 ls airdb.io
    # - s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY ls -r s3://airdb.me/${REPO}/
    #- s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY put ${BUILDER_PACKAGE} s3://airdb.me/${REPO}/
    #- s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY put --acl-public dist/* -r s3://airdb.me/
    #- s3cmd --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_KEY ls -r s3://airdb.me/websites/airdb.io/
    - curl  "${WechatMSG}?status=success&from=travis&info=https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
    #after_failure:
    #    - curl  "https://awsapi.airdb.vip/travis-ci?status=failure&info=https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
before_deploy:
    - curl airdb.com/before_deploy
#deploy:
    #- provider: releases
    #  user: $GITHUB_USERNAME
    #  password: $GITHUB_PASSWORD
    #  file: fcweb.tar.gz
    #  skip_cleanup: true
    #  on: 
    #    branch: master
    #  #tags: true
    #    provider: s3
    #    access_key_id: $AWS_ACCESS_KEY_ID
    #    secret_access_key: $AWS_SECRET_KEY
    #    bucket: $BUCKET
    #    #local_dir: "./releases"
    #    key: "fcweb.tar.gz"
    #    upload-dir: "fcweb"
    #    #skip_cleanup: false
    #    #default_text_charset: 'utf-8'
#    on:
#        branch: master
after_deploy:
    - curl airdb.com/after_deploy
after_script:
    - curl airdb.com/after_scritp
