notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required

language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"

# cache components
before_install:
    - env
    - npm run build
install:
      - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
      - curl airdb.com/install
before_script:
    - curl airdb.com/before_script
script:
    - npm run build
after_success:
    - curl  "https://awsapi.airdb.vip/travis-ci?status=success&info=https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
after_failure:
    - curl  "https://awsapi.airdb.vip/travis-ci?status=failure&info=https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
before_deploy:
    - curl airdb.com/before_deploy
after_deploy:
    - curl airdb.com/after_deploy
after_script:
    - curl airdb.com/after_scritp
